# profiling: https://www.bigbinary.com/blog/zsh-profiling
#zmodload zsh/zprof

# Created by `pipx` on 2025-10-27 20:52:17
export PATH="$PATH:/Users/julien.muetton/.local/bin"

# BEGIN SCFW MANAGED BLOCK
alias npm="scfw run npm"
alias pip="scfw run pip"
alias poetry="scfw run poetry"
export SCFW_DD_AGENT_LOG_PORT="10365"
export SCFW_DD_LOG_LEVEL="ALLOW"
export SCFW_HOME="/Users/julien.muetton/.scfw"
# END SCFW MANAGED BLOCK

# Export bindings a la emacs, vim bindings seemed unreliable
#bindkey
# And partial search in history with up/down arrows
# up/down-line-or-beginning-search navigates within multiline buffers first,
# then falls back to prefix history search at the top/bottom line.
autoload -U up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey '^[[A' up-line-or-beginning-search
bindkey '^[[B' down-line-or-beginning-search
bindkey "^?" backward-delete-char

# History
HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=5000
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt incappendhistory
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# Completion with highlight and arrow navigation
autoload -U compinit && compinit
zstyle ':completion:*' menu select
# Shift+TAB select previous item in completion
zmodload zsh/complist
bindkey -M menuselect "${terminfo[kcbt]}" reverse-menu-complete

[[ ! -d $HOME/.zshrc-pre.d ]] || {
    for file in $HOME/.zshrc-pre.d/*; do
        source "$file"
    done
}

# Include all the common configuration
[[ ! -f $HOME/.shrc ]] || {
    source $HOME/.shrc
}

[[ ! -d $HOME/.zshrc.d ]] || {
    for file in $HOME/.zshrc.d/*; do
        source "$file"
    done
}

# Syntax highlight in commands
# https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/INSTALL.md
# brew install zsh-syntax-highlighting
if [ -f /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] ; then
    source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

# profiling: https://www.bigbinary.com/blog/zsh-profiling
#zprof
