# Path to home
export HOME="${HOME:-"/home/julien"}"

# Include all the common configuration
source $HOME/.shrc

for file in $HOME/.bashrc-pre.d/*; do
    source "$file"
done
for file in $HOME/.bashrc.d/*; do
    source "$file"
done
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"
. "$HOME/.cargo/env"
